name: Bug Report
description: Report a bug in Simply Refined
title: "[BUG]: Replace with a brief title about the bug"
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for reporting a problem! Please fill out the details below as completely as possible.

  - type: dropdown
    id: modpack_version
    attributes:
      label: Simply Refined Version
      description: Which version of Simply Refined are you using?
      options:
        - 1.21.10 | 1.1.1a (Alpha)
        - 1.21.9 | 1.3.1b (Beta)
        - 1.21.8 | 1.2.6 (Stable)
        - 1.21.7 | 1.2.5 (Stable)
        - 1.21.6 | 1.2.5 (Stable)
        - 1.20.1 | 1.0.3 (Stable)
        - Other (Please Specify In Bug Description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Describe the bug clearly and concisely, including steps on how to reproduce the bug, and what you expected to happen.
      placeholder: Bug description, steps to reproduce, expected results...
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: "Please confirm the following:"
      options:
        - label: I have searched existing issues to make sure this bug wasn’t already reported
          required: true
