name: Bug Report
description: Report a bug in Simply Refined
title: "[BUG]: Replace with a brief title about the bug"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for reporting a problem! Please fill out the details below as completely as possible.

  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft Version
      description: Which Minecraft version are you using?
      options:
        - 1.21.9
        - 1.21.8
        - 1.21.7
        - 1.21.6
    validations:
      required: true

  - type: dropdown
    id: modpack_version
    attributes:
      label: Simply Refined Version
      description: Which Simply Refined version are you using?
      options:
        - 1.10.0a (Alpha)
        - 1.2.1 (Stable)
        - Other (Please Specify In Description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: What happened, and what did you expect to happen?
      placeholder: "Describe the bug clearly and concisely."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Latest Log / Spark Profiler
      description: In Modrinth, click on your Simply Refined modpack, then go to **Logs > Share** and paste the **mclo.gs** link below. Please do not paste the text content of your logs here, or your issue will be closed.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this bug wasn’t already reported
          required: true
