blank_issues_enabled: false
contact_links:
  - name: 🔗 [Discord] Simply Refined Support
    url: https://discord.gg/PnTmBpuJXP
    about: Need help or have a suggestion to improve Simply Refined? Join the Discord for further assistance!
