name: Crash Report
description: Report a crash in Simply Refined
title: "[CRASH]: Replace with a brief title about the crash"
labels: [Crash]
body:
  - type: markdown
    attributes:
      value: |
        ## Crash Report
        Thanks for reporting a problem! Please fill out the details below as completely as possible.

  - type: dropdown
    id: modpack_version
    attributes:
      label: Simply Refined Version
      description: Which version of Simply Refined are you using?
      options:
        - 1.21.10 | 1.1.0a (Alpha)
        - 1.21.9 | 1.2.1b (Beta)
        - 1.21.8 | 1.2.5 (Stable)
        - 1.21.7 | 1.2.4 (Stable)
        - 1.21.6 | 1.2.4 (Stable)
        - 1.20.1 | 1.0.3 (Stable)
        - Other (Please Specify In Crash Description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Crash
      description: Describe the crash clearly and concisely, including steps on how to reproduce the crash if possible.
      placeholder: Crash description, steps to reproduce (if possible) . . .
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Latest Crash Log
      description: In Modrinth, click on your Simply Refined modpack, then go to **Logs > Share** and paste the **mclo.gs** link below. Please do not paste the text content of your latest log here, or your issue will be closed.
      placeholder: E.g. mclo.gs/abcdefg
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: "Please confirm the following:"
      options:
        - label: I have searched existing issues to make sure this crash wasn’t already reported
          required: true
